name: CI

on: [push, pull_request]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Setup node.js (for pyright)
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          
      - name: Run type checking
        run: |
          npm install -g pyright
          pip install -r requirements.txt
          pip install .
          pyright --lib --verifytypes discord --ignoreexternal

  black:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install black
        run: pip install black

      - name: run linter
        uses: wearerequired/lint-action@v1
        with:
          black: true
          black_args: ". --line-length 120"